1. 如果一个函数用noexcpt修饰了，但是函数定义中仍然throw了异常，那么此异常无法被try...catch代码块捕获且程序在throw异常处中断
